module.exports = {
  apps: [{
    name: 'encodium',
    script: '/home/coder/encodium/server.js',
    cwd: '/home/coder/encodium',
    exec_mode: 'fork',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '512M',
    env: {
      NODE_ENV: 'production',
      DB_HOST: 'localhost',
      DB_PORT: '3306',
      DB_USER: 'encodium',
      DB_PASS: 'jeROha7QSHFgCHjEwe5Ke7Qm',
      DB_NAME: 'encodium',
      JWT_SECRET: 'AxOe9jDVKgyW0Rr0nLX69KDzGem9sAV4T4d03fNj6RBmYpjl',
      PORT: '4000',
      MEDIA_DIR: '/home/coder/encodium/data/media',
      ENCODE_DIR: '/home/coder/encodium/data/encoded',
      MAX_WORKERS: '2',
    },
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    error_file: '/home/coder/encodium/data/logs/error.log',
    out_file: '/home/coder/encodium/data/logs/out.log',
    merge_logs: true,
  }],
};
